### ISSUE TITLE
CRUD-операции

### ISSUE THREAD

**Issue by Ari100kratov** [Ilya181297/FirstProject#3]
1. Доделать операции с записями - редактировать и удалить.\
2. Реализовать бесконечный цикл - после каждой команды выводились таблица и команды

**Comment by Ilya181297** [comment]
прочитать куча, стэк, ООП(Базовые понятия).

**Comment by Ilya181297** [comment]
[developer](https://github.com/Ilya181297/FirstProject/pull/4)

**Comment by Ilya181297** [comment]
https://github.com/Ilya181297/FirstProject/pull/4
